# Generated by Django 3.1.4 on 2021-01-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='slug',
            field=models.SlugField(default='SOME STRING'),
        ),
        migrations.AlterField(
            model_name='show',
            name='show',
            field=models.CharField(choices=[('Chicago', 'Chicago'), ('Wicked', 'Wicked'), ('The Phantom of the Opera', 'The Phantom of the Opera'), ('Come From Away', 'Come From Away'), ('To Kill a Mockingbird', 'To Kill a Mockingbird')], max_length=200),
        ),
    ]
