# Generated by Django 3.1.4 on 2021-01-12 11:57

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_auto_20210112_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='show'),
        ),
        migrations.AlterField(
            model_name='spent',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
