# Generated by Django 3.1.4 on 2021-01-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0003_auto_20210107_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
