# Generated by Django 3.1.4 on 2021-01-11 13:05

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0004_auto_20210107_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='show',
            field=models.CharField(choices=[('Chicago', 'Chicago'), ('Wicked', 'Wicked'), ('The Phantom of the Opera', 'The Phantom of the Opera'), ('Come From Away', 'Come From Away'), ('To Kill a Mockingbird', 'To Kill a Mockingbird')], max_length=200),
        ),
        migrations.AlterField(
            model_name='show',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='show'),
        ),
        migrations.AlterField(
            model_name='spent',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
